receivers:
  otlp/1:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5001
  otlp/2:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5002

processors:
  batch:

exporters:
  kafka/1:
    protocol_version: 1.0.0
    brokers: emig-ehns.servicebus.windows.net:9093
    topic: emig-eh1
    auth:
      tls:
        insecure: false
      sasl:
        username: $$ConnectionString
        password: $CONNECTION_STRING_EH1
        mechanism: PLAIN
  kafka/2:
    protocol_version: 1.0.0
    brokers: emig-ehns.servicebus.windows.net:9093
    topic: emig-eh2
    auth:
      tls:
        insecure: false
      sasl:
        username: $$ConnectionString
        password: $CONNECTION_STRING_EH2
        mechanism: PLAIN

service:
  pipelines:
    metrics/1:
      receivers: [otlp/1]
      processors: [batch]
      exporters: [kafka/1]
    metrics/2:
      receivers: [otlp/2]
      processors: [batch]
      exporters: [kafka/2]